<style>
html {
	position: relative;
	min-height: 100%;
}
body {
	/* Margin bottom by footer height */
	margin-bottom: 72px;
}
.footer {
	position: absolute;
	bottom: 0;
	width: 100%;
	/* Set the fixed height of the footer here */
	height: 72px;
	background-color: #f5f5f5;
}
</style>

<footer class="footer">
	<div class="container">
		<p class="text-muted text-center" style="margin: 20px 0">
			&copy; 2000 - 2019 American Computer Estimating, Inc.   |   1155 Phoenixville Pike, Ste 109 West Chester, PA 19380   |   <a href="privacy.aspx">Privacy</a>   |   <a href="disclaimer.aspx">Disclaimer</a>
			<br/>
			Website design and web code Copyright &copy; 2015 - 2019 Anthony Puppo. All rights reserved.
		</p>
	</div>
</footer>

<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-1644909-1', 'auto');
	ga('send', 'pageview');

</script>

<!--<script type="text/javascript" src="http://ec2-52-2-157-8.compute-1.amazonaws.com/ace-livechat/php/app.php?widget-init.js"></script>-->
