<!-- sidebar navigator -->
<div class="panel panel-borderless" style="box-shadow: none;">
	<div class="panel-heading" style="font-size: 1.8em; color: black; text-align: center;">
		<strong class="">Services</strong>
	</div>
	<!--<h3 style="text-align: center"><b>Services</b></h3>-->
	<ul id="side-menu" class="nav nav-stacked side-menu" style ="text-align: center">
		<li><div class="nav-divider"></div></li>
		<li><a id="autoreview" href='autoreview.aspx'><span class="fancy-font">AutoReview</span></a></li>
		<li><a id="propreview" href='propreview.aspx'><span class="fancy-font">PropReview</span></a></li>
		<li><a id="specialty" href='specialty.aspx'><span class="fancy-font">Specialty</span></a></li>
		<li><a id="subreview" href='subreview.aspx'><span class="fancy-font">SubReview</span></a></li>
		<li><a id="photoquote" href="photoquote.aspx"><span class="fancy-font">PhotoQuote</span></a></li>
		<li><div class="nav-divider"></div></li>
	</ul>
	<!--<ul class="nav nav-stacked side-menu">
		<li><div class="nav-divider"></div></li>
		<li><a href='http://www.bodyshopnet.com' target="_blank" style="color: royalblue">BodyShopNet</a></li>
		<li><div class="nav-divider"></div></li>
	</ul>-->
</div>

