<!-- Static top navbar -->
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<!--<a class="navbar-brand" href="#">Project name</a>-->
		</div>
		<div id="navbar" class="navbar-collapse collapse" style="font-size: medium">
			<ul class="nav navbar-nav">
				<li id="home-tab"><a href="index.aspx">Home</a></li>
				<li id="about-us-tab"><a href="about.aspx">About Us</a></li>
				<!--<li id="e-claims-tab"><a href="e-claims.aspx">E-Claims</a></li>-->
				<li id="employment-tab"><a href="employment.aspx">Employment</a></li>
				<li id="faq-tab"><a href="faq.aspx">FAQ</a></li>
				<li id="industry-links-tab"><a href="industry-links.aspx">Industry Links</a></li>
				<li id="contact-us-tab"><a href="contact.aspx">Contact Us</a></li>
			</ul>
			<ul class="navbar-right socialmedia-list">
				<li><a href="//www.facebook.com/acetheclaimsreviewcompany" class="facebook" target="_blank"></a></li>
				<li><a href="//twitter.com/AceClaimsReview" class="twitter" target="_blank"></a></li>
				<li><a href="//www.linkedin.com/company/american-computer-estimating" class="linkedin" target="_blank"></a></li>
			</ul>
		</div> <!--/.nav-collapse -->
	</div> <!--/.container-fluid -->
</nav>
